# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poshtest2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from backend import *
from PyQt5 import QtCore, QtGui, QtWidgets

MAIN_WINDOW = None

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(522, 647)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(522, 647))
        MainWindow.setMaximumSize(QtCore.QSize(522, 647))

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(275, 10, 161, 21))
        self.lineEdit_email.setObjectName("lineEdit_email")

        self.pushButton_startstop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_startstop.setGeometry(QtCore.QRect(440, 40, 75, 23))
        self.pushButton_startstop.setObjectName("pushButton_startstop")
        self.pushButton_startstop.clicked.connect(lambda: clicked_start(self)) # clicked connect


        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(210, 10, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")

        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(275, 40, 161, 21))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(173, 40, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")

        self.checkBox_savelogin = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_savelogin.setGeometry(QtCore.QRect(440, 10, 81, 17))
        self.checkBox_savelogin.setObjectName("checkBox_savelogin")

        self.doubleSpinBox_speed = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_speed.setGeometry(QtCore.QRect(170, 100, 171, 20))
        self.doubleSpinBox_speed.setObjectName("doubleSpinBox_speed")
        self.doubleSpinBox_speed.setValue(0.8)

        self.spinBox_followamount = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_followamount.setGeometry(QtCore.QRect(170, 130, 170, 20))
        self.spinBox_followamount.setObjectName("spinBox_followamount")

        self.label_followedusers = QtWidgets.QLabel(self.centralwidget)
        self.label_followedusers.setGeometry(QtCore.QRect(90, 100, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_followedusers.setFont(font)
        self.label_followedusers.setObjectName("label_followedusers")

        self.label_followedusers_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_followedusers_2.setGeometry(QtCore.QRect(10, 130, 221, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_followedusers_2.setFont(font)
        self.label_followedusers_2.setObjectName("label_followedusers_2")

        self.label_followedusers_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_followedusers_3.setGeometry(QtCore.QRect(370, 100, 151, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_followedusers_3.setFont(font)
        self.label_followedusers_3.setObjectName("label_followedusers_3")

        self.lcdNumber_followed = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_followed.setGeometry(QtCore.QRect(370, 130, 141, 21))
        self.lcdNumber_followed.setObjectName("lcdNumber_followed")

        self.listWidget_followed = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_followed.setGeometry(QtCore.QRect(10, 160, 501, 341))
        self.listWidget_followed.setObjectName("listView_followed")

        self.label_description = QtWidgets.QLabel(self.centralwidget)
        self.label_description.setGeometry(QtCore.QRect(10, 514, 501, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_description.setFont(font)
        self.label_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_description.setObjectName("label_description")

        self.label_licence = QtWidgets.QLabel(self.centralwidget)
        self.label_licence.setGeometry(QtCore.QRect(350, 580, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_licence.setFont(font)
        self.label_licence.setObjectName("label_licence")

        self.dateTimeEdit_expiration = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_expiration.setGeometry(QtCore.QRect(460, 580, 51, 22))
        self.dateTimeEdit_expiration.setReadOnly(True)
        self.dateTimeEdit_expiration.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateTimeEdit_expiration.setObjectName("dateTimeEdit_expiration")

        self.checkBox_randomizespeed = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_randomizespeed.setGeometry(QtCore.QRect(10, 100, 70, 31))
        self.checkBox_randomizespeed.setObjectName("checkBox_randomizespeed")

        self.label_searchterm = QtWidgets.QLabel(self.centralwidget)
        self.label_searchterm.setGeometry(QtCore.QRect(15, 70, 251, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_searchterm.setFont(font)
        self.label_searchterm.setStyleSheet("")
        self.label_searchterm.setObjectName("label_searchterm")

        self.lineEdit_searchterm = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_searchterm.setGeometry(QtCore.QRect(275, 70, 161, 21))
        self.lineEdit_searchterm.setObjectName("lineEdit_searchterm")

        self.frame_logo = QtWidgets.QFrame(self.centralwidget)
        self.frame_logo.setGeometry(QtCore.QRect(10, 10, 151, 51))
        self.frame_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")


        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_startstop.setText(_translate("MainWindow", "Begin"))
        self.label_email.setText(_translate("MainWindow", "Email:"))
        self.label_password.setText(_translate("MainWindow", "Password:"))
        self.checkBox_savelogin.setText(_translate("MainWindow", "Save Login?"))
        self.label_followedusers.setText(_translate("MainWindow", "Speed:"))
        self.label_followedusers_2.setText(_translate("MainWindow", "Follow Amount:"))
        self.label_followedusers_3.setText(_translate("MainWindow", "Followed Users"))
        self.label_description.setText(_translate("MainWindow", "Recommended speed: .8\n"
"Leave follow amount 0 for infinite follows\n"
"Buy me here: link"))
        self.label_licence.setText(_translate("MainWindow", "Licence Valid Until:"))
        self.dateTimeEdit_expiration.setDisplayFormat(_translate("MainWindow", "M/d/yyyy"))
        self.checkBox_randomizespeed.setText(_translate("MainWindow", "Randomize"))
        self.label_searchterm.setText(_translate("MainWindow", "Profile Link / Search Term:"))


def run():
    global MAIN_WINDOW

    app = QtWidgets.QApplication(sys.argv)
    MAIN_WINDOW = QtWidgets.QMainWindow()

    ui = Ui_MainWindow()
    ui.setupUi(MAIN_WINDOW)

    MAIN_WINDOW.show()
    sys.exit(app.exec_())