
# Window for gui
MAIN_WINDOW = None
COMPANIES = []


def get_companies():
    return COMPANIES


def set_companies(arr):
    global COMPANIES
    COMPANIES = arr


def drop_dupes(dataframe):
    cols = []
    for col in dataframe.columns:
        if (col in cols) or (".1" in col):
            dataframe.drop(col, axis=1, inplace=True)
        cols.append(col)
    return dataframe


OPERATING_REVENUE = "Operating Revenue"
COST_OF_GOODS_SOLD = "Cost of Goods Sold"
GROSS_PROFIT = "Gross Profit"
SG_AND_A_EXPENSE = "SG&A Expense"
RESEARCH_AND_DEVELOPMENT_EXPENSE = "Research & Development Expense"
SPECIAL_INCOME_AND_CHARGES = "Special Income and Charges"
OPERATING_INTEREST_EXPENSE = "Operating Interest Expense"
NET_OPERATING_INTEREST_INCOME = "Net Operating Interest Income"
TOTAL_OPERATING_EXPENSES = "Total Operating Expenses"
OPERATING_INCOME = "Operating Income"
OTHER_INCOME_AND_EXPENSES = "Other Income & Expenses"
PRE_TAX_INCOME = "Pre-Tax Income"
PROVISION_FOR_INCOME_TAXES = "Provision for Income Taxes"
INCOME_FROM_CONTINUING_OPERATIONS = "Income from Continuing Operations"
NORMALIZED_INCOME = "Normalized Income"
EBITDA = "EBITDA"
RECONCILED_DEPRECIATION = "Reconciled Depreciation"
EBIT = "EBIT"
EPS_BASIC_FROM_CONTINUING_OPERATIONS = "EPS Basic from Continuing Operations"
NORMALIZED_BASIC_EPS = "Normalized Basic EPS"
EPS_DILUTED_FROM_CONTINUING_OPERATIONS = "EPS Diluted from Continuing Operations"
NORMALIZED_DILUTED_EPS = "Normalized Diluted EPS"
AVERAGE_BASIC_SHARES_OUTSTANDING = "Average Basic Shares Outstanding"
AVERAGE_DILUTED_SHARES_OUTSTANDING = "Average Diluted Shares Outstanding"
DIVIDEND_PER_SHARE = "Dividend Per Share"
OTHER_OPERATING_EXPENSES = "Other Operating Expenses"
CASH_AND_EQUIVALENTS = "Cash & Equivalents"
SHORT_TERM_INVESTMENTS = "Short Term Investments"
CASH_AND_SHORT_TERM_INVESTMENTS = "Cash & Short Term Investments"
ACCOUNTS_RECEIVABLES = "Accounts Receivables"
TOTAL_RECEIVABLES = "Total Receivables"
RAW_MATERIALS = "Raw Materials"
WORK_IN_PROCESS = "Work In Process"
FINISHED_GOODS = "Finished Goods"
INVENTORIES = "Inventories"
OTHER_CURRENT_ASSETS = "Other Current Assets"
TOTAL_CURRENT_ASSETS = "Total Current Assets"
PROPERTIES = "Properties"
MACHINE_FURNITURE_AND_EQUIPMENT = "Machine, Furniture & Equipment"
CONSTRUCTION_IN_PROGRESS = "Construction in Progress"
GROSS_PP_AND_E = "Gross PP&E"
ACCUMULATED_D_AND_A = "Accumulated D&A"
NET_PP_AND_E = "NET PP&E"
GOODWILL = "Goodwill"
OTHER_INTANGIBLE_ASSETS = "Other Intangible Assets"
GOODWILL_AND_INTANGIBLES = "Goodwill & Intangibles"
LONG_TERM_INVESTMENTS = "Long Term Investments"
LONG_TERM_RECEIVABLES = "Long Term Receivables"
LONG_TERM_DEFERRED_ASSETS = "Long Term Deferred Assets"
OTHER_LONG_TERM_ASSETS = "Other Long Term Assets"
TOTAL_LONG_TERM_ASSETS = "Total Long Term Assets"
TOTAL_ASSETS = "Total Assets"
ACCOUNTS_PAYABLE = "Accounts Payable"
TOTAL_PAYABLES = "Total Payables"
ACCRUED_EXPENSES = "Accrued Expenses"
PAYABLES_AND_ACCRUED_EXPENSES = "Payables and Accrued Expenses"
OTHER_CURRENT_BORROWINGS = "Other Current Borrowings"
CURRENT_PORTION_OF_LONG_TERM_DEBT = "Current Portion of Long Term Debt"
CURRENT_DEFERREDREVEUE = "Current DeferredReveue"
OTHER_CURRENT_LIABILITIES = "Other Current Liabilities"
TOTAL_CURRENT_LIABILITIES = "Total Current Liabilities"
NON_CURRENT_PORTION_OF_LONG_TERM_DEBT = "Non-Current Portion of Long Term Debt"
LONG_TERM_DEFERRED_TAX_LIABILITIES = "Long Term Deferred Tax Liabilities"
NON_CURRENT_DEFERRED_LIABILITIES = "Non-Current Deferred Liabilities"
OTHER_LONG_TERM_LIABILITIES = "Other Long Term Liabilities"
TOTAL_LONG_TERM_LIABILITIES = "Total Long Term Liabilities"
TOTAL_LIABILITIES = "Total Liabilities"
TOTAL_CAPITAL_STOCK = "Total Capital Stock"
RETAINED_EARNINGS = "Retained Earnings"
ACCRUED_COMPREHENSIVE_INC = "Accrued Comprehensive Inc"
SHAREHOLDERS_EQUITY = "Shareholders Equity"
LAND_AND_IMPROVEMENTS = "Land & Improvements"
CURRENT_TAX_PAYABLE = "Current Tax Payable"
NET_INCOME = "Net Income"
OPERATING_GAINS_LOSSES = "Operating Gains Losses"
TOTAL_DEPRECIATION_AND_AMORTIZATION = "Total Depreciation & Amortization"
DEFERRED_TAXES = "Deferred Taxes"
STOCK_BASED_COMPENSATION = "Stock Based Compensation"
OTHER_NONCASH_ITEMS = "Other Noncash Items"
CHANGE_IN_RECEIVABLES = "Change in Receivables"
CHANGE_IN_INVENTORIES = "Change in Inventories"
CHANGE_IN_PAYABLES_AND_ACCRUED_EXPENSE = "Change in Payables and Accrued Expense"
CHANGES_IN_OTHER_WORKING_CAP = "Changes in Other Working Cap"
CHANGES_IN_WORKING_CAPITAL = "Changes in Working Capital"
CASH_FROM_OPERATIONS = "Cash from Operations"
NET_CHANGE_IN_CAPITAL_EXPENDITURES = "Net Change in Capital Expenditures"
FREE_CASH_FLOW = "Free Cash Flow (5YR AVG: $14.93B)"
NET_CHANGE_IN_PP_AND_E = "Net Change in PP&E"
NET_CHANGE_IN_INTANGIBLES = "Net Change in Intangibles"
ACQUISITIONS_AND_DISPOSITIONS = "Acquisitions/Dispositions"
CASH_FROM_INVESTING = "Cash from Investing"
NET_CHANGE_IN_LONG_TERM_DEBT = "Net Change in Long Term Debt"
NET_CHANGE_IN_SHORT_TERM_DEBT = "Net Change in Short Term Debt"
NET_DEBT_ISSUANCE = "Net Debt Issuance"
COMMON_STOCK_PAYMENTS = "Common Stock Payments"
NET_COMMON_EQUITY_ISSUED_PURCHASED = "Net Common Equity Issued (Purchased)"
TOTAL_COMMON_DIVIDENDS_PAID = "Total Common Dividends Paid"
TOTAL_DIVIDENDS_PAID = "Total Dividends Paid"
CASH_FROM_OTHER_FINANCING_ACTIVITIES = "Cash from Other Financing Activities"
CASH_FROM_FINANCING = "Cash from Financing"
BEGINNING_CASH = "Beginning Cash"
CHANGE_IN_CASH = "Change in Cash"
CASH_FOREIGN_EXCHANGE_ADJUSTMENT = "Cash Foreign Exchange Adjustment"
ENDING_CASH = "Ending Cash"
ISSUANCE_OF_DEBT = "Issuance of Debt"
DEBT_REPAYMENT = "Debt Repayment"
REPURCHASE_OF_CAPITAL_STOCK = "Repurchase of Capital Stock"
COMMON_STOCK_ISSUANCE = "Common Stock Issuance"
